Update gki-kernel.yml

diff --git a/.github/workflows/gki-kernel.yml b/.github/workflows/gki-kernel.yml
--- a/.github/workflows/gki-kernel.yml
+++ b/.github/workflows/gki-kernel.yml
@@ -106,17 +106,29 @@ jobs:
           PATCH_PATH: ${{ inputs.patch_path }}
         run: |
           cd $GITHUB_WORKSPACE/android-kernel
-          echo "[+] KernelSU setup"
+          set -eux
           GKI_ROOT=$(pwd)
           echo "[+] GKI_ROOT: $GKI_ROOT"
-          echo "[+] Copy KernelSU driver to $GKI_ROOT/common/drivers"
-          ln -sf $GITHUB_WORKSPACE/KernelSU/kernel $GKI_ROOT/common/drivers/kernelsu
-          echo "[+] Add KernelSU driver to Makefile"
-          DRIVER_MAKEFILE=$GKI_ROOT/common/drivers/Makefile
-          grep -q "kernelsu" $DRIVER_MAKEFILE || echo "obj-y += kernelsu/" >> $DRIVER_MAKEFILE
-          echo "[+] Apply KernelSU patches"
-          cd $GKI_ROOT/common/ && git apply $GITHUB_WORKSPACE/KernelSU/.github/patches/$PATCH_PATH/*.patch
-          echo "[+] KernelSU setup done."
+          if test -d "$GKI_ROOT/common/drivers"; then
+               DRIVER_DIR="$GKI_ROOT/common/drivers"
+          elif test -d "$GKI_ROOT/drivers"; then
+               DRIVER_DIR="$GKI_ROOT/drivers"
+          else
+               echo '[ERROR] "drivers/" directory is not found.'
+               echo '[+] You should modify this scrpit by yourself.'
+               exit 127
+          fi
+          test -d "$GKI_ROOT/KernelSU" || git clone https://github.com/tiann/KernelSU
+          cd "$GKI_ROOT/KernelSU"
+          git stash && git pull
+          cd "$GKI_ROOT"
+          echo "[+] GKI_ROOT: $GKI_ROOT"
+          echo "[+] Copy kernel su driver to $DRIVER_DIR"
+          test -e "$DRIVER_DIR/kernelsu" || ln -sf "$GKI_ROOT/KernelSU/kernel" "$DRIVER_DIR/kernelsu"
+          echo '[+] Add kernel su driver to Makefile'
+          DRIVER_MAKEFILE=$DRIVER_DIR/Makefile
+          grep -q "kernelsu" "$DRIVER_MAKEFILE" || printf "\nobj-y += kernelsu/\n" >> "$DRIVER_MAKEFILE"
+          echo '[+] Done.'
 
       - name: Symbol magic
         run: |
